apiVersion: v1
kind: Service
metadata:
  name: jwt-manager-service
  labels:
    app: jwt-manager-service
spec:
  ports:
  - port: 80
    name: http
    targetPort: 3400
  selector:
    app: jwt-manager
---
apiVersion: v1
imagePullSecrets:
- name: tpp-registry
kind: ServiceAccount
metadata:
  name: jwt-manager-service-account
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-manager
  labels:
    app: jwt-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: jwt-manager
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'jwt-manager'
        vault.hashicorp.com/agent-inject-secret-pk.pem: 'kv/data/jwt-manager/production'
        vault.hashicorp.com/agent-inject-template-pk.pem: |
          {{- with secret "kv/data/jwt-manager/production" -}}
          {{ .Data.data.privKey }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-pubk.pem: 'kv/data/jwt-manager/production'
        vault.hashicorp.com/agent-inject-template-pubk.pem: |
          {{- with secret "kv/data/jwt-manager/production" -}}
          {{ .Data.data.pubKey }}
          {{- end -}}
    spec:
      serviceAccountName: jwt-manager-service-account
      containers:
      - name: jwt-manager
        image: localhost:5000/jwt-manager-latest 
        imagePullPolicy: "Always"
        env:
          - name: PORT
            value: "3400"
          - name: VAULT_SECRET_FILE_PATH
            value: /vault/secrets/
          - name: TOKEN_EXPIRE
            value: "2 days"
          - name: REF_TOKEN_EXPIRE
            value: "7 days"
        ports:
        - containerPort: 3400
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi